ARG BUILD_ENV="build:dev"
ARG EXPLORER_BRANCH=suite
ARG WALLET_BRANCH=suite

FROM node:16 as stage-suite
ARG BUILD_ENV
WORKDIR /app/camino-suite

COPY ./ /app/camino-suite/
RUN yarn install
RUN yarn $BUILD_ENV


FROM europe-west3-docker.pkg.dev/pwk-c4t-dev/internal-camino-dev/camino-suite-explorer:$EXPLORER_BRANCH as stage-explorer


FROM europe-west3-docker.pkg.dev/pwk-c4t-dev/internal-camino-dev/camino-suite-wallet:$WALLET_BRANCH  as stage-wallet



FROM nginx:1.18
COPY --from=stage-suite /app/camino-suite/dist/ /usr/share/nginx/html
COPY --from=stage-explorer /app/camino-block-explorer/dist/ /usr/share/nginx/html/explorer
COPY --from=stage-wallet /app/camino-wallet/dist/ /usr/share/nginx/html/wallet
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./nginx.conf /etc/nginx/conf.d/default.conf