import { StoreProvider } from '@rebuild/shared/store';
import { Navbar } from '@rebuild/ui';
import './global.css';

export const metadata = {
  title: 'Welcome to camino-suite',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center w-full">
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
