
//Graphs if using CO2 Charts
export const typesMeter = {
    BAR: 'BAR',
    TIME_SERIES: 'TIME_SERIES',
    COUNTRIES_BAR: 'COUNTRIES_BAR',
    LINE_CHART: 'LINE_CHART'
};

//Statistic if using Statistics Charts
export const typesStatistic = {
    DAILY_TRANSACTIONS: 'DAILY_TRANSACTIONS',
    UNIQUE_ADRESSES: 'UNIQUE_ADRESSES',
    DAILY_TOKEN_TRANSFER: 'DAILY_TOKEN_TRANSFER',
    GAS_USED: 'GAS_USED',
    ACTIVE_ADDRESSES: 'ACTIVE_ADDRESSES',
    GAS_AVERAGE_PRICE: 'GAS_AVERAGE_PRICE',
    GAS_AVERAGE_LIMIT: 'GAS_AVERAGE_LIMIT',
    AVERAGE_BLOCK_SIZE: 'AVERAGE_BLOCK_SIZE',
}